// Generated by CoffeeScript 1.6.3
/*
ThinWire(R) Ajax RIA Framework
Copyright (C) 2003-2008 Custom Credit Systems
Copyright (c) 2013 Ted C Howard

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/

var tw_BorderImage;

tw_BorderImage = (function() {
  function tw_BorderImage() {}

  tw_BorderImage.prototype._box = null;

  tw_BorderImage.prototype._borderSize = -1;

  tw_BorderImage.prototype._borderSizeSub = -1;

  tw_BorderImage.prototype.setBox = function(box) {
    return this._box = box;
  };

  tw_BorderImage.prototype.setBorderSize = function(borderSize) {
    this._borderSize = borderSize;
    return this._borderSizeSub = borderSize * 2;
  };

  tw_BorderImage.prototype.setWidth = function(width) {
    if ((this._box == null) || this._borderSize < 0 || width < 0) {
      return;
    }
    width -= this._borderSizeSub;
    if (width < 0) {
      width = 0;
    }
    return this._box.style.width = "" + width + "px";
  };

  tw_BorderImage.prototype.setHeight = function(height) {
    if ((this._box == null) || this._borderSize < 0 || height < 0) {
      return;
    }
    height -= this._borderSizeSub;
    if (height < 0) {
      height = 0;
    }
    return this._box.style.height = "" + height + "px";
  };

  tw_BorderImage.prototype.setImage = function(image, width, height) {
    var style;
    style = this._box.style;
    return style.borderImage = "" + (tw_Component.expandUrl(image, true)) + " " + this._borderSize + " fill stretch";
  };

  tw_BorderImage.prototype.destroy = function() {
    this._box.style.borderImage = '';
    return this._box = null;
  };

  return tw_BorderImage;

})();
